defaults:
  - CLIPVisionModelTaskPool@: _template_L14
  - /dataset/image_classification/test@test_datasets:
      - stanford-cars
      - resisc45
      - eurosat
      - svhn
      - gtsrb
      - mnist
      - dtd
